name: CI

on: [push]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        luaVersion: ["5.3"]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: leafo/gh-actions-lua@master
      with:
        luaVersion: ${{ matrix.luaVersion }}

    - uses: leafo/gh-actions-luarocks@master

    - name: test lua
      run: lua -e 'print("hi from lua")'

    - name: test luarocks
      run: |
        echo $PATH
        env | grep LUA
        luarocks
        luarocks path
        luarocks install lpeg
        luarocks install dkjson
        luarocks install argparse
        lua -e 'print(require("dkjson").encode({{Foo = "BAR"}, {1, 2, 3}}, {indent=true}))'
